# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'azdevarmconn'
            subscriptionId: '0ab23bef-dece-46e9-9ff4-ea78713214cf'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'azdevrg'
            location: 'Central US'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/hafisarmpipeline/azuredeploy.parameters.json'
            csmParametersFile: '$(Build.SourcesDirectory)/hafisarmpipeline/azuredeploy.json'
            deploymentMode: 'Validation'